baseURL = "https://crossbar.red/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Crossbar"
metaDataFormat = "yaml"
paginate = 15
enableRobotsTXT = true

[sitemap]
	changefreq = "monthly"
	priority = 0.5
	filename = "sitemap.xml"

# settings tbd
# canonifyUrls = 
# googleAnalytics = 
#
# [permalinks]
#
# [taxonomies]
# 
# [indexes]
# 
# [params]
# 
# [author]
# 
