baseURL = "https://crossbar.red/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Crossbar"
metaDataFormat = "yaml"
paginate = 15
enableRobotsTXT = true
canonifyUrls = true

[permalinks]
  posts = "/:year/:month/:slug/"

[params]
	owner = "Shawn Medero"
	description = ""

[sitemap]
	changefreq = "monthly"
	priority = 0.5
	filename = "sitemap.xml"

# settings tbd
# googleAnalytics = 
#
# [permalinks]
#
# [taxonomies]
# 
# [indexes]
# 
# [author]
# 
