baseURL = "https://crossbar.red/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Crossbar"
metaDataFormat = "yaml"
paginate = 15
enableRobotsTXT = true
# can't think of a good reason to set this
# canonifyUrls = false

[params]
	owner = "Shawn Medero"
	description = ""

[sitemap]
	changefreq = "monthly"
	priority = 0.5
	filename = "sitemap.xml"

[taxonomies]
	tag = "tags"
	archive = "archives"

[permalinks]
	posts = "/:year/:month/:day/:slug/"

# settings tbd
# googleAnalytics = 
#
# [indexes]
# 
# [author]
# 
